plugins:
  # Leverage stern (https://github.com/stern/stern) to output logs.
  stern:
    shortCut: Ctrl-Y
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
      - deployments
    command: stern
    background: false
    args:
      - --tail
      - 50
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  b64edit:
    shortCut: Shift-E
    confirm: false
    description: Edit (base64 decoded)
    scopes:
      - secrets
      - configmaps
      - all
    dangerous: true
    background: false
    command: sh
    args:
      - -c
      - kubectl-b64edit --context "$CONTEXT" --namespace "$NAMESPACE" "$RESOURCE_NAME${RESOURCE_GROUP:+.$RESOURCE_GROUP}" "$NAME"